const mongoose = require('mongoose');

const campaignSchema = new mongoose.Schema({
  name: { type: String, required: true },
  segmentDescription: { type: String, required: true }, // Natural language description
  segmentQuery: { type: Object, required: true }, // MongoDB query object generated by AI
  messageTemplate: { type: String, required: true },
  status: { type: String, enum: ['DRAFT', 'SENDING', 'COMPLETED'], default: 'DRAFT' },
  stats: {
    sent: { type: Number, default: 0 },
    delivered: { type: Number, default: 0 },
    opened: { type: Number, default: 0 },
    clicked: { type: Number, default: 0 },
    failed: { type: Number, default: 0 }
  },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Campaign', campaignSchema);
